version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  db-init:
    build:
      context: ./backend
      dockerfile: data/data_import/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - default

  backend:
    build: ./backend
    depends_on:
      - db-init
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - default

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"  # Map port 80 in the container to 3000 on the host
    networks:
      - default

volumes:
  db_data:
