version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_USER=citybike
    - MYSQL_PASSWORD=CitybikePW1!
    - MYSQL_DATABASE=city_bike
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init-scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 20s
      retries: 10

  db-init:
    build:
      context: ./data
      dockerfile: data_import/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=citybike
      - DB_PASSWORD=CitybikePW1!
      - MYSQL_DATABASE=city_bike
      - STATION_CSV=/app/bike_data/stations_data/stations.csv
      - JOURNEY_FILES_PATTERN=/app/bike_data/journeys_data/chunked_journeys_data/*_part_*.csv
    networks:
      - default

  backend:
    build: ./backend
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/city_bike
      - SPRING_DATASOURCE_USERNAME=citybike
      - SPRING_DATASOURCE_PASSWORD=CitybikePW1!
    networks:
      - default

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - default

volumes:
  db_data:
